batch_size: 128
board_size:
- 28
- 28
device: !!python/object/apply:torch.device
- cpu
epochs: 50
exp_name: trained_models/snn_experiment
hidden_dim: 128
input_dim: 50
map_shape:
- 9
- 9
max_steps: 32
max_time: 32
min_time: 1
net_type: snn
num_actions: 5
num_agents: 5
num_workers: 3
obstacles: 5
sensing_range: 6
tests_episodes: 100
train:
  batch_size: 32
  max_time_dl: 25
  min_time: 5
  mode: train
  nb_agents: 5
  root_dir: dataset/5_8_28
valid:
  batch_size: 8
  max_time_dl: 25
  min_time: 5
  mode: valid
  nb_agents: 5
  root_dir: dataset/5_8_28
