action_layers: 1
batch_size: 128
board_size:
- 28
- 28
channels:
- 16
- 16
- 16
device: !!python/object/apply:torch.device
- cpu
encoder_dims:
- 64
encoder_layers: 1
epochs: 50
exp_name: 5_8_28\gnn_v1_k2
graph_filters:
- 2
last_convs:
- 400
map_shape:
- 5
- 5
max_steps: 32
max_time: 32
min_time: 1
net_type: gnn
node_dims:
- 128
num_agents: 8
num_workers: 3
obstacles: 10
sensing_range: 6
strides:
- 1
- 1
- 1
- 1
- 1
tests_episodes: 25
train:
  max_time_dl: 25
  min_time: 5
  mode: train
  nb_agents: 5
  root_dir: dataset\5_8_28
