exp_name: 'trained_models/snn_experiment'  # Use forward slashes (works on all OS)

# RSNN parameters — Add these
net_type: 'snn'            # ✅ Key change to activate framework_snn.py
input_dim: 9              # ✅ Assuming 9x9 local FOV per agent (adjust as needed)
hidden_dim: 128            # Hidden size in SNN layer
num_actions: 5             # Assuming 5 possible movements (up, down, left, right, stay)

# You can remove or ignore CNN, GNN, encoder, policy MLP params

# Training
epochs: 50
tests_episodes: 100
device: cuda               # or 'cpu' if CUDA not available

# Simulation
board_size: [18,18]
map_shape: [5,5]
num_agents: 5
obstacles: 5
max_steps: 32
max_time: 32
sensing_range: 6           # Possibly 9x9 input

# Data Loading
min_time: 1
num_workers: 3
batch_size: 128
train:
    root_dir: 'dataset/5_8_28'   # ✅ Use forward slashes for cross-platform compatibility
    mode: 'train'
    min_time: 5
    max_time_dl: 25
    nb_agents: 5
valid:
    root_dir: 'dataset/5_8_28'
    mode: 'valid'
    min_time: 5
    max_time_dl: 25
    nb_agents: 5
